# This is a basic workflow to help you get started with Actions

name: Build Test

# Controls when the workflow will run
on:


  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    strategy:
      fail-fast: true
      matrix:
        buildConfig: ["Release", "Debug"]       
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Prepare msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Restore
        run: nuget restore CodeWalker.sln

      # Runs a set of commands using the runners shell
      - name: Build
        run: msbuild CodeWalker.sln /t:CodeWalker /p:Configuration=${{ matrix.buildConfig }}
